//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestorantEntities : DbContext
    {
        public RestorantEntities()
            : base("name=RestorantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<yemekler> yemekler { get; set; }
        public virtual DbSet<masalar> masalar { get; set; }
        public virtual DbSet<roller> roller { get; set; }
        public virtual DbSet<rezervasyon> rezervasyon { get; set; }
        public virtual DbSet<kullanicilar> kullanicilar { get; set; }
    }
}
