//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezervasyon
    {
        public int rezervasyon_id { get; set; }
        public System.DateTime rezervasyon_tarihi { get; set; }
        public System.TimeSpan rezervasyon_saati { get; set; }
        public int masa_id { get; set; }
        public int kişi_sayisi { get; set; }
        public int kullanici_id { get; set; }
        public string musteri_email { get; set; }
        public string musteri_tel { get; set; }
        public string musteri_adi { get; set; }
        public string musteri_soyadi { get; set; }
    
        public virtual masalar masalar { get; set; }
        public virtual kullanicilar kullanicilar { get; set; }
    }
}
